### ISSUE TITLE
Feedback 10 - Caching of Security Artefacts

### ISSUE THREAD

**Issue by acccivan** [cdr-register/register#10]
The ACCC is requesting feedback from the community on the security practices within their organisation on caching security artefacts. 

The intention is to identify current practices and tolerances of cache staleness to help drive recommendations on caching.

As this information is sensitive, feedback can be provided as email to: CDRTeam@accc.gov.au

**Comment by NationalAustraliaBank** [comment]
Are there any expected metrics that can be provided to help us model our feedback on? For example, expected size, and the frequency of updates for different events (e.g. new participant, change in accreditation status). We expect that the frequency of some of these events could also be driven by the frequency and outcomes of on-going participant compliance assurance audits, reviews and activities.

**Comment by commbankoss** [comment]
Based on the current CDR technical standards a cache age of 30 to 60 minutes would be sufficient, as long as there is no time lag between when the ACCC updates the cache (via GetDataRecepients) and notifies participants of the update (via RequestMetaDataUpdate). 

However, we require more details regarding the internal design and process of the Register. The lifecycle of updates will determine the Commonwealth Bank’s approach and the frequency of requests made to update the cache.

**Comment by JamesMBligh** [comment]
Considering the obligations on Banks under other regulatory frameworks (such as CPS 234) perhaps there should be flexibility allowed for cache periods with the ACCC providing an “at least” requirement rather than a minimum requirement.

For instance, cached metadata should be refreshed “at least” once every x hours.

Would that work better for the Banks?

**Comment by spikejump** [comment]
This feedback does not comment on ACCC's original request for security practices, however, it relates to Caching of metadata/security artifacts.

Are all participants required to cache metadata of all other participants?  Including those that they will not communicate with?  This is particularly relevant to ADRs since ADRs will not care about other ADRs metadata and may only care of some of the Data Holders metadata.

It seems very expensive for all participants to hit ACCC Registry to query for update when they may not care about the update.

If this makes sense then can there be enhancements to the following two APIs?
1. metadata update request from Registry
enhanced with a list of participant IDs that require refresh
1. discovery APIs
enhanced with query parameter for desired participant ID or with a new POST method to include a list of participant IDs in the body like other POST methods.

Going along this path, the spec currently mentions of

> Metrics will be captured on participant cache refreshes to ensure they conform to recommendations

This statement will no longer be viable if participants aren't required to always callback into the Registry.

**Comment by JamesMBligh** [comment]
I have always assumed (but happy to be corrected) that recipients would only obtain and cache holder data and vice versa.  Also, for refresh,  this would be an unusual situation where there is risk perceived.

If both of those assumptions are true then I don’t think there is a significant imposte on the recipients or holders for caching the metadata.  They would need at least this data to make their services work.

**Comment by CDR-Register-Stream** [comment]
@spikejump As commented by @JamesMBligh the expectation would be that Data Holders are retrieving Data Recipient metadata and Data Recipients are retrieving Data Holder metadata only via the Register Discovery API. There is no requirement for them to query all information about all participants. With the proposed Static Client Registration Model, a force refresh notification on Data Holder change would only result in Data Recipients being notified, and vice versa.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your feedback. For reference, the caching rules are defined in the Register design and can be found at: https://cdr-register.github.io/register/#metadata-cache-management
