### ISSUE TITLE
Process for Holder changing RegisterDataHolderBrandServiceEndpoint

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#109]
Could guidance be given by the ACCC around the process Holders are required to follow for updates to [RegisterDataHolderBrandServiceEndpoint](https://cdr-register.github.io/register/#tocSregisterdataholderbrandserviceendpoint)?

The reason we ask this question is that should a Holder update their `infosecBaseUri` significantly (ie. hostname change) this represents a new issuer and would consequently require new Dynamic Client Registrations to be established by ADR's and, as a consequence, new consents to be reestablished for all previous sharing agreements.

By way of reference, in the UK it is expected banks would use out of band means to notify TPPs ("Recipients") well in advance to ensure continuity.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for raising this issue.

Guidance will need to be in place to ensure changes to the issuer due to hostname changes are well planned and the repercussions well understood by all participants. 

Guidance on release management still needs to be provided by the ACCC and will need to incorporate this topic. I will leave this issue open to track its progress.

**Comment by perlboy** [comment]
See https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/354
