### ISSUE TITLE
Request for Clarification on future dated scopes in SSA

### ISSUE THREAD

**Issue by commbankoss** [cdr-register/register#117]
Commonwealth Bank is seeking clarification on the follow:

- Would an ADR’s SSA issued for July go-live contain future dated scopes that are not currently supported (e.g.: Scheduled payments and direct debits)?
- If it would, what behavior is expected when in authorization flow an ADR requests a scope that is currently not supported?
  - Should the ADH reject the request; or
  - Should the ADH allow the request if there are other valid scopes, but ignore scopes currently not supported?
- If it won’t, then do we expect ADRs to submit a new SSA when additional scopes are introduces?

**Comment by perlboy** [comment]
> If it won’t, then do we expect ADRs to submit a new SSA when additional scopes are introduces?

Isn't this the purpose of the `PUT` call in the DCR?

**Comment by commbankoss** [comment]
@CDR-Register-Stream and @CDR-API-Stream, Commonwealth Bank requests a response be provided urgently.

**Comment by CDR-Register-Stream** [comment]
@commbankoss Thanks for your query and @perlboy, thanks for your input.

The current[ CDR Register design](https://cdr-register.github.io/register/#dynamic-client-registration) describes what scopes will currently be returned when requesting an SSA. They are as follows:
```
"scope":
        "bank:accounts.basic:read
         bank:accounts.detail:read
         bank:transactions:read
         bank:payees:read
         bank:regular_payments:read
         common:customer.basic:read
         common:customer.detail:read
         cdr:registration"
```

In the July timeframe, this list of scopes is not going to change. As new functionality and therefore scopes become available, the GetSSA request from the Register will reflect the scopes that are available for the given point in time.

The ADR will be required to update their registration as per the `PUT` call as described in the [Client Registration Management section](https://cdr-register.github.io/register/#client-registration-management)

So to directly answer your questions:

> Would an ADR’s SSA issued for July go-live contain future dated scopes that are not currently supported (e.g.: Scheduled payments and direct debits)?

No

> If it would, what behavior is expected when in authorization flow an ADR requests a scope that is currently not supported?
> Should the ADH reject the request; or
> Should the ADH allow the request if there are other valid scopes, but ignore scopes currently not supported?

Although this scenario is intended to be avoided, there is a timing risk that the CDR Register exposes the new scopes before the DH supports them (although we would expect this window of opportunity to be minimised as we coordinate roll out). I would prefer that the Data Holder returned an error rather than accepting the scopes and filtered out the invalid ones, otherwise we risk obscuring the issue and making debugging more challenging. 

> If it won’t, then do we expect ADRs to submit a new SSA when additional scopes are introduces?

Yes, this is correct

**Comment by perlboy** [comment]
Hi @CDR-Register-Stream,

Specifically on this:
> > If it would, what behavior is expected when in authorization flow an ADR requests a scope that is currently not supported?
> > * Should the ADH reject the request; or
> > * Should the ADH allow the request if there are other valid scopes, but ignore scopes currently not supported?
> Although this scenario is intended to be avoided, there is a timing risk that the CDR Register exposes the new scopes before the DH supports them (although we would expect this window of opportunity to be minimised as we coordinate roll out).
> We would need to balance out the benefit of either filtering the scopes out or returning an error,
> * If we return an error we reduce the risk of obscuring the issue and making debugging more a little easier.
> * If we filter out the invalid scopes, we allow ADRs to update their registrations independent of scopes, given they have no control over the scopes which are populated in their SSA.

The underlying standard RFC7591 (and the UK one by proxy) for `scope` registration states:
> String containing a space-separated list of scope values (as described in Section 3.3 of OAuth 2.0 [RFC6749]) that the client can use when requesting access tokens.  The semantics of values in this list are service specific.  If omitted, an authorization server MAY register a client with a default set of scopes.

Section 3.3 of OAuth 2.0 says:
> The authorization server MAY fully or partially ignore the scope requested by the client, based on the authorization server policy or the resource owner's instructions.  If the issued access token scope is different from the one requested by the client, the authorization server MUST include the "scope" response parameter to inform the client of the actual scope granted.

On the above basis ignoring unsupported scopes would be valid provided the response contains the `scope` response parameter (which it should since it's mandated as Required by the Register DCR).

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your input.

Current thinking is that the unsupported scopes should be ignored during a DCR post and put request. This ensures that any changes to the scopes supplied by the Register within the SSA doesn't result in a breakage between the DH and ADR registration.

The other point of discussion is how to handle scopes during the consent flow, which is currently being discussed in the CDS Standards Maintenance [issue 243](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/243)

**Comment by CDR-Register-Stream** [comment]
@ryderwj raises a good question in the CDS thread
https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/243#issuecomment-653999729

Levels of accreditation will need to be considered for the future and it is perhaps reduction in level of accreditation could occur. Therefore scopes would be reduced and a mechanism to ensure that ADRs update their registrations to reflect this, would be required

**Comment by CDR-Register-Stream** [comment]
In order to move this discussion forward, I have summarised current thinking, highlighted gaps and invite feedback on our recommendation

### The Problem
As the CDR Regime progresses, different Data Holders will have different requirements on functionality they are required to support. This is reflected as Data Holders supporting different authorisation scopes.

In the future it is expected there will be different levels of accreditation. This will mean that ADRs will only be authorised to use a subset of scopes that Data Holders may support

Registrations and token requests must align to what scopes Data Holders support and what scopes ADRs are authorised to request. When requests do not meet this requirement, how should Data Holders respond?

#### Current process for ADRs
1.	ADRs retrieve an SSA from the Register. This SSA contains all scopes that the ADR is authorised to use
2.	ADR queries OIDC Discovery configuration document to discover Data Holder supported scopes
3.	ADR Registers with this Data Holder and receives a registration for these scopes
4.	ADR will make requests for tokens using the scopes that are recorded against this registration

### Issues
#### Registration
If an ADR creates or updates a registration, the SSA may contain scopes which the Data Holder doesn’t support. The Data Holder can respond in one of two ways

**Option 1.** 
   Return an error and prevent the creation/update of the registration

   If an error is returned, future updates to registrations will be blocked, even if these updates are not related to scopes. To prevent an error being returned, the ADR could provide a subset of scopes as part of the registration, however this information would not have been part of the signed SSA and therefore would need to be verified somehow.


**Option 2.**
Filter out unsupported scopes and return a registration for only the scopes that the Data Holder supports and the ADR requested

The ADR will receive a list of scopes that map to this registration as part of the creation/update so will be aware of what they are authorised to request

As raised by @perlboy , RFC 7591 and Section 3.3 of OAuth2.0 encourages this position 

---

Our current position is that DHs implement against option 2. 
We would welcome feedback on the recommendation that the CDR Register design is updated to reflect that DHs **MUST** ignore extraneous scopes

### Consent Flow
Please refer to the discussion on [issue 243 in the CDS]( https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/243)

### Outstanding considerations
#### Reduction in scopes
In the future, it is anticipated that ADRs may have a reduction in their accreditation level, resulting in a reduction in the number of authorisation scopes it is allowed to use in registration and requests for tokens.

ADRs may also retire part of their usecase from market and update their registrations to reflect this.

We still need to determine how to ensure that ADRs update their registrations to reflect the reduction in scopes, handle currently issued consents for scopes which are no longer authorised, and ensure that DHs don’t inadvertently disclose consumer data to an ADR via a scope which has been de-authorised by the Register. 

#### Extensions to the standards
DHs may extend the standards and therefore create new scopes to support these extensions. Currently the Register does not cater for this use case as SSAs are currently DH agnostic.

Any new scopes would require namespace conventions to be adopted (such as using their x-HID convention as defined in the [Extensibility section](https://consumerdatastandardsaustralia.github.io/standards/#extensibility
) of the CDS

**Comment by CDR-Register-Stream** [comment]
Feedback for this issue can now be considered **closed**

Upon receipt of a registration creation or update, when scopes are provided that are not supported by the Data Holder, the Data Holder will be expected to filter out unsupported scopes. A registration will be returned for only the scopes that the Data Holder supports which are common to those that the ADR requested

**Comment by perlboy** [comment]
This advice is not currently followed by the ACCC Conformance Test Suite. The CTS is currently rejecting DCR responses which do not include all of it's requested scopes.

**Comment by CDR-Register-Stream** [comment]
Closing as complete


This CTS issue was resolved in a previous version and is no longer present but @perlboy, appreciate you highlighting the issues
