### ISSUE TITLE
The specification of API for dirct debit

### ISSUE THREAD

**Issue by nickdfgithub** [cdr-register/register#131]
Hi cdr-register

Can you clarify the specification of Get Direct Debits For Specific Accounts at CDS portal? The defination give POST but not GET.
"POST /banking/accounts/direct-debits" 

I though it could be typo.

Bank of China Sydney Branch
Feng DONG(Nick)

**Comment by nils-work** [comment]
Hi @nickdfgithub 
I think this question belongs in [CDS Standards Maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues), but it's a POST because the 'Specific Accounts' are passed in the body of the POST request as described by the `body` parameter of that [endpoint](https://consumerdatastandardsaustralia.github.io/standards/index.html#get-direct-debits-for-specific-accounts).

**Comment by CDR-Register-Stream** [comment]
@nickdfgithub Thank you for your query. @nils-work is correct and this question belongs in[ CDS Standards Maintenance](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues). 

@nils-work, thanks for providing this guidance.

Closing
