### ISSUE TITLE
Use of Global CA as Root Authority

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#149]
It is understood that the ACCC is currently issuing certificates from an Intermediary CA with a Trust Chain that terminates at the `DigiCert High Assurance EV Root CA`, a certificate authority which is globally trusted by all operating system certificate authorities. While a full trust chain is a "good idea" it introduces the distinct possibilities that participants are not implementing effective controls with regards to the MTLS verification they are conducting.

The [test strategy makes no mention](https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/cdr-phase-2-test-strategy-november-2020) of this constraint despite it being documented clearly in the DSB Standards:

>The presented Client transport certificate MUST be issued by the CDR Certificate Authority (CA). The Server MUST NOT trust Client transport certificates issued by other authorities.
> The presented Server transport certificate MUST be issued by the CDR Certificate Authority (CA). The Client MUST NOT trust Server transport certificates issued by other authorities.
> End points for transferring CDR Data that are classified as not requiring authentication do not require the use of [MTLS].

Can the ACCC please verify that:
1) They are issuing certificates which are trusted globally?
2) They are testing participants endpoints to ensure that sufficient controls are in place blocking participants conducting mix-up attacks using non-Register CA certificates?

For the record, this risk was raised by myself **numerous** times so it is disappointing [this risk not only exists](https://github.com/ConsumerDataStandardsAustralia/standards/issues/65#issuecomment-489319440) but does not appear to be specifically tested.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query.

The certificate management section of the documentation does not currently outline the trust model being used in the CDR.

Please stay tuned and we will provide this information to answer these questions you have raised.

**Comment by perlboy** [comment]
An update on this based on information now known.

1. The Register CA issues certificates from an intermediate private certificate authority for comms between Recipients and Holders. This includes the secured IDP endpoints (ie. non-browser based) and the resource servers delivering CDR Data
2. The unauthenticated Register API which serves `GetSoftwareProductsStatus`, `GetDataRecipientsStatus`, `GetDataRecipients` calls is delivered via the aforementioned DigiCert Globally trusted CA.
3. The unauthenticated Register API is not secured with DNSSEC resulting in exposure to DNS poisoning

As a result of (2) and (3) a mildly successful DNS poisoning attack _could_ result in the immediate and permanent revocation of all data recipients in the ecosystem through the serving of `SURRENDERED` status at the `GetDataRecipientsStatus` endpoint with a rogue public CA certificate and, in line with the Register guidelines, it would be expected this would be propagated within 5 minutes.

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your query.

We're seeking to verify our understanding of the problem is inline with what you're raising.

Our understanding is:

- You want to know whether verification of Mutual TLS is planned as part of the November iterations of CTS
- A problem exists where a rogue third party certificate authority may sign certificates which can be used to person-in-the-middle non-mTLS encrypted traffic with API endpoints
- DNSSec is not enabled meaning that DNS cache poising may be possible

Is this an accurate summarisation of this issue?


If so:

- We will be looking to implement some mTLS test cases as part of the November release of CTS. These will not comprehensively cover all possible scenarios but will act as a foundation for further test cases moving forwards.
- Internal dialogue has been opened for some time to discuss the merits of transport security, certificate authority trusts and how we can better approach this problem (using a dedicated CDR-signed TLS certificate for all non-mTLS traffic) and/or signing/encrypting HTTP response bodies. We will provide an update in the future as to how this will occur, but it may take some time to design and implement.
- We will provide a response to DNSSec late next week.

As an immediate defensive control, vendors can monitor or pin certificate root authorities and DNS vendor-side. No IP rotations are planned to occur in the immediate future, and all API certificates will be provisioned using Digicert for the foreseeable future unless otherwise notified.

**Comment by CDR-Register-Stream** [comment]
@perlboy, as per our previous post, here is an update on our DNSSEC issue.
 
As of the posting of this message. The CDR team is currently still in the process of developing an effective remedial option that will patch the DNSSEC (DNS poisoning) vulnerability you disclosed to us earlier this year.
 
As we continue to work on this solution, any further comments/reply to our previous message (on the 2nd of November 2020) would prove to be exceptionally informative. 

We would additionally like to offer an 'out of band' method for continued communication, please advise us if you are willing to continue discussions via said 'Out of Band' method.

**Comment by perlboy** [comment]
@CDR-Register-Stream this thread went dead. I see `cdr.gov.au` still has no DNS records and is consequently susceptible to relatively trivial poisoning attacks.

Regarding communication, I'm confused why this requires further explanation from me however various members of the government have my contact details but engagement seems to be at the governments leisure. After 3 years of providing analysis and endless free consulting I now have higher priorities and therefore will instead await clear regulator instructions for implementations I'm associated with rather than attempting to predict and resolve bureaucratic "own goals".

Related elaboration on this footnote here: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/354

Closing ticket.
