### ISSUE TITLE
When Software Product Status not Active can SSAs be retrieved?

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#159]
As per title, when software product status is set to any state other than ACTIVE can SSA's be retrieved?

Secondly, if they can be retrieved, should they be honoured by Holders for registration?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thank you for your query.

Clients will not be able to retrieve an access token from the CDR Register when inactive and therefore will not be able to retrieve an SSA.

There is conceivably a window of opportunity between the retrieval of an access token and the issuance of an SSA, where the software product status is set to inactive between these events. The SSA lifetime has been set to [10 mins](https://cdr-register.github.io/register/#dynamic-client-registration) in order to minimise the opportunity for this scenario being exploited.

Data Holders are not expected to check the status prior to registration as the current controls are deemed sufficient. This simplification is by design.

Data Holders must [check statuses ](https://cdr-register.github.io/register/#data-holder-responsibilities) prior to disclosing consumer data.

Please let me know if this answers your question.

**Comment by perlboy** [comment]
Hi @CDR-Register-Stream,

It does, thank you. 

It might be helpful if the documentation could be updated to be explicit about this?
https://cdr-register.github.io/register/#getsoftwarestatementassertion-ssa

**Comment by perlboy** [comment]
Closing see https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/354
