### ISSUE TITLE
Feedback 18 - Branding

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#18]
This thread has been created to allow for feedback on logo branding for participants within the CDR.

As part of the discovery process, both [Data Holders](https://cdr-register.github.io/register/#tocSregisterdataholderserviceendpoint) and [Data Recipients](https://cdr-register.github.io/register/#tocSregisterproductserviceendpoint) will be required to present a logo and consent logo URIs.

These logos are to be used by other participants to present Data Holders or Data Recipients within their user interfaces. However, the DSB CX stream is not prescriptive on how these user interfaces should be designed:

[CX Guidelines](https://consumerdatastandards.org.au/wp-content/uploads/2019/07/CX_Guidelines_v0.9.5.pdf)
Note the following:
_The guidelines do not necessarily prescribe how to put the rules into effect, but aligning with these is recommended to help provide a consistent and familiar CDR ecosystem that consumers trust._

As a starting point, we present the following conventions:
1. Logo URIs should reference SVG vectors files
2. Logo SVG files should be optimised to be viewable at 50 x 50px

Further details will be provided for how consent logos should be presented   

All feedback is welcome.

**Comment by NationalAustraliaBank** [comment]
NAB has the following feedback on the Branding topic.

A minimum size or size constraint should be a **guideline** rather than a mandatory requirement. A hard requirement can restrict what is possible in the implementation, and this was observed in NPP with the PayID branding.

Instead, NAB suggests that guidelines consider logos that are visible and useful at small scales as well as large scales. An impact if this was to be adopted would be to the fields in the [Register Discovery APIs](https://cdr-register.github.io/register/#consumer-data-right-cdr-register-discovery-api) for the logo URI, if multiple logos will be supported.

**Comment by commbankoss** [comment]
Commonwealth Bank supports NAB’s comment and agree that there should not be a mandatory constraint on size and instead a guideline be in place. We agree that use cases for both small and large scale images will be required and adopting a change to the registry discovery API to support multiple logos is the most reasonable solution.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your feedback.
On consultation with the CX team, no constraints on branding will be mandated at launch of the CDR.

This position may change as the CDRmatures
