### ISSUE TITLE
Decision Proposal 22 - Certificate Usage

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#22]
This thread has been created to capture, document and obtain feedback on Certificate Usage for CDR Participants

The decision proposal is attached below (updated).
[Decision.Proposal.22-Certificate.Usage.pdf](https://github.com/cdr-register/register/files/3564242/Decision.Proposal.22-Certificate.Usage.pdf)

All feedback is welcome.

**Comment by perlboy** [comment]
Hi there,

Great to see a second decision proposal come out, great work!

Just for clarity, the term "Certificate" here is being used with respect to the TLS(-MA) components? I ask because the description of approach starts with a statement with respect to the JWKS (separate from TLS(-MA)) and then explains issues with respect to the TLS(-MA) components? If so it seems JWKS be specifically called out as NOT in scope for this document with a reference to the still open decision #15 and comments regarding JWKS be cleaned up so it's clear?

With respect to TLS(-MA), I note no reference at all to Unauthenticated APIs (Product Info). I can understand why this might be descoped although I'd point out that right now the Authenticated APIs appear to directly reference the active Product in `BankingProduct` (a secured payload) as `productCategory` and `productName`. Ie. In order to gain a full copy of the data model appears to require crossing auth and unauthed boundaries. Relative to this doc, it seems explicit guidelines with respect to Public API, even if it is "up to the DH", be specified. Alternatively guidance could be given that product info be supplied within an authenticated domain as well or that the unauthenticated (aka "public") be secured with an ACCC CA cert.

I've previously explained the broader impacts of this from a security perspective: https://github.com/ConsumerDataStandardsAustralia/standards/issues/65#issuecomment-489319440

Thanks,

Stuart

**Comment by JamesMBligh** [comment]
Hi @perlboy, just to clarify, the CDR standards have specifically not accommodated linkage between the Account Detail data (ie. data on a specific instantiated Account) and Product Detail (ie. data on on-market offers).  Schema and reference data (like the ProductCategory enum) is aligned to allow for comparisons to be made.

**Comment by JamesMBligh** [comment]
The recommended changes in the decision proposal looks reasonable to me.  It also looks like it simplifies things somewhat and keeps good architectural boundaries in place (ie. transport security is only used for securing transport and not given additional meaning for managing application level processes).

**Comment by NationalAustraliaBank** [comment]
NAB assumes that the certificates under this decision proposal relates to TLS, not JWKS covered under Decision Proposal  https://github.com/cdr-register/register/issues/15.

Another issue with the current approach that proposes to separate the ADR InfoSec and Resource client certificates is that this breaks the Holder of Key mechanism to bind the client certificate to the token, given that the InfoSec client certificate presented to the /token DH InfoSec endpoint will be different to the Resource client certificate presented to the DH resource endpoints.

NAB supports the proposed new approach for the TLS certificate requirement for both Data Holders and Accredited Data Recipients.

For the DH error response described under point 3 of the description of the new approach, the [CDS](https://consumerdatastandardsaustralia.github.io/standards/#http-response-codes) provides an approach to form the error response. HTTP Status Code 403, and a standardised error payload & error code should be defined this scenario.

**Comment by WestpacOpenBanking** [comment]
Westpac is supportive of the proposed new approach for certificate usage, especially the flexibility to choose how many server certificates and associated domains are needed. We agree that suspension should not involve the revocation of transport certificates, and agree with the approach to revocation. If the approach is adopted, the error circumstances, messages and HTTP response codes should be standardized for the benefit of data recipients.

**Comment by CDR-Register-Stream** [comment]
@perlboy and all,
Yes this decision proposal is describing certificate usage as certificates issues by the CA and used for TLS(-MA) components. The decision proposal has been updated to clarify

**Comment by CDR-Register-Stream** [comment]
All, this issue has now been resolved and the proposed approach will be adopted.
Thanks to all the contributors helping to bring this decision to a close.

[Decision - Decision Proposal 22 Certificate Usage.pdf](https://github.com/cdr-register/register/files/3593373/Decision.-.Decision.Proposal.22.Certificate.Usage.pdf)
