### ISSUE TITLE
Who issues the client IDs used by DR 

### ISSUE THREAD

**Issue by versent1Jas** [cdr-register/register#3]
Do the Data Recipients get clientIDs as a result of successful registration with ACCC? 
ClientIDs refer to the values used by DRs for the request object specified [https://consumerdatastandardsaustralia.github.io/standards/#request-object]:
{
  "alg": "PS256",
  "typ": "JWT",
  "kid": "123"
}
{
  "aud": "https://www.recipient.com.au",
  "response_type": "code id_token",
  **"client_id": "12345",**
  "redirect_uri": "https://www.recipient.com.au/coolstuff",
  "scope": "openid",
  "state": "af0ifjsldkj",
  "nonce": "n-0S6_WzA2Mj",
  "claims": {
    "id_token": {
      "sharing_duration": "7776000",
      "acr": {
        "essential": true,
        "values": ["urn:cds.au:cdr:3"]
      }
    },
    "userinfo": {
      "sharing_duration": "7776000",
      "given_name": null,
      "family_name": null
    }
  }
}

**Comment by JamesMBligh** [comment]
There would appear to be a few options for client ID assignment:

1. **Recipient selects an ID and enters into the Register**.  There would seem to be little value in this option as the Client ID is not intended to have semantic meaning.  It’s just an ID.
1. **Holder assigns an ID**.  This would be hard to implement with static registration.  It is unclear how the holder would communicate the ID to the recipient and every recipient would need to maintain a database of IDs for multiple holders.
1. **Client ID assigned by the Register**.  This would seem to be the logical choice since recipients must be included in the register and holders must obtain the metadata anyway.  The only complication with this is that, depending on the choice of implementation, the holder may need to map the Client ID to an internal registration ID in the Authorise server.

I don’t think there is another option but I may have missed something.  If there is no other option then the third approach would seem logical.  Interested in other opinions though.

**Comment by fahadbinrahat** [comment]
@JamesMBligh - In your option 3, the Client ID in JWT token would be the ID if the [individual application](https://cdr-register.github.io/register/#tocSregisterproduct) not the [data recipient id](https://cdr-register.github.io/register/#tocSregisterdatarecipient). 

Is this correct?

**Comment by fahadbinrahat** [comment]
@JamesMBligh  could you please comment if following Data Recipient registration and subsequent interaction with Data holders scenarios are correct?

-Data Recipients register with ACCC Register and obtain a unique ID (statically).
-Data Holders are notified
-Data Holders update their cache and update Data Recipients/software products list
-Data Recipients registers themselves and their software products with Data Holders using Dynamic Client Registration method and obtain a unique ID for that Data Holder (Data Holder creates a map of this ID and client's ACCC ID which will be used in subsequent registration status checks)
-Data Recipients use unique id allocated by Data Holder as Client Id in all interactions with the Data holder (Data Recipients will not use ACCC's Register allocated IDs with Data Holders.)

**Comment by JamesMBligh** [comment]
> @JamesMBligh - In your option 3, the Client ID in JWT token would be the ID of the [individual application](https://cdr-register.github.io/register/#tocSregisterproduct) not the [data recipient id](https://cdr-register.github.io/register/#tocSregisterdatarecipient).
> 
> Is this correct?

That was my assumption.

**Comment by JamesMBligh** [comment]
> @JamesMBligh could you please comment if following Data Recipient registration and subsequent interaction with Data holders scenarios are correct?
> 
> -Data Recipients register with ACCC Register and obtain a unique ID (statically).
> -Data Holders are notified
> -Data Holders update their cache and update Data Recipients/software products list
> -Data Recipients registers themselves and their software products with Data Holders using Dynamic Client Registration method and obtain a unique ID for that Data Holder (Data Holder creates a map of this ID and client's ACCC ID which will be used in subsequent registration status checks)
> -Data Recipients use unique id allocated by Data Holder as Client Id in all interactions with the Data holder (Data Recipients will not use ACCC's Register allocated IDs with Data Holders in authentication and authorisation flows)

I don’t believe the last two steps are accurate as dynamic registration is not being used.  My understanding is that data recipients use the client ID provided by the register to identify themselves to holders.

**Comment by fahadbinrahat** [comment]
@JamesMBligh 

The second last step was in accordance with specs as stated [here](https://cdr-register.github.io/register/#client-registration)

_"This standard allows for Accredited Data Recipients to dynamically register with Data Holders within the system. However, the CDR Register is designed using Static Client Registration to satisfy the above requirements"_

**Comment by CDR-Register-Stream** [comment]
@fahadbinrahat The Client Authentication section of the CDR-Register design outlines the client ids which should be used by Data Recipients to identify themselves to Data Holders: https://cdr-register.github.io/register/#client-authentication

As for the comments above regarding Dynamic Registration, the current design outlines the proposed model of Static Client Registration.

**Comment by fahadbinrahat** [comment]
@JamesMBligh - I guess you are referring to first point on [this ](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication) link which is about Data Recipients authentication at Data Holder end? (https://consumerdatastandardsaustralia.github.io/standards/#client-authentication)

Besides this, your comment:- _"**My understanding is that data recipients use the client ID provided by the register to identify themselves to holders.**"_ .

This would require extra processing due to required ID translation on Data Holder end on each API call, moreover there may not be Out-of-the-Box support for this sort of Id translation in IdAMs.

**Comment by bmangalaganesh** [comment]
This area has been bothering me for a few weeks now.

My reading of the specs states - **Dynamic Registration** is not supported at the moment.

(1) This discussion has focussed primarily on client-id, I don't see any information about client-secrets. Client-id and Client-secret go hand-in-hand in the OAuth2/OIDC flows.

Generally a Client ID is associated with an _App_ and not an _Organisation_ (such as a ADR/TPP). A TPP might build multiple applications and each application needs its own Client ID and Client Secret.

The Static Client Registration that is described in the specs does not talk about an App and it talks about the organization and is likely done only once for the lifetime of the ADR.

Are we making an assumption here that a ADR will have only one application?

(2) The Discovery APIs do not provide a mechanism to share the secrets (from what I see in the request/response). How is the secret disseminated to the ADRs (both from a first time use as well as secret rotations if required as an API governance policy of the Data Holder).

(3) The UK banks (such as Barclays, Lloyds group) expect the TPP (ADR in our parlance) to work with their developer portals and go through a process by which the client-ids and client-secrets are obtained (even though a dynamic registration spec exists it is not widely used by the CMA9.

Appreciate some clarity in this space.

**Comment by JamesMBligh** [comment]
Yes, that is correct.  Alternatively every Data Recipient implements a mapping of client ID to Data Holder.  This would also not out of the box.

**Comment by CDR-Register-Stream** [comment]
The Register design facilitates [Dynamic Client Registration](https://cdr-register.github.io/register/#client-registration) where Data Holders issue client ids.

Closing this issue
