### ISSUE TITLE
Certificate Authority Signing Algorithm

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#36]
Hi there,

With reference to this: https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/35

Can the ACCC please clarify if the Register intends (now or in the future) to use and potentially offer Elliptic Curve (as opposed to exclusively RSA) signed certificates to participants from the ACCC Register. If not it halves the implementation requirement in this area of the Consumer Data Standards.

Thanks in advance.

**Comment by perlboy** [comment]
As a footnote on this, this is related to the Standards when using ECDSA for ECDH during various interactions related to the specified cipher list elements ```TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384``` and ```TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256``` so mainly relates to software statement assertions (versus MTLS CA choices).

The [Australian Cyber Security Centre provides](https://www.cyber.gov.au/sites/default/files/2019-12/22.%20ISM%20-%20Guidelines%20for%20Using%20Cryptography%20%28November%202019%29.pdf) (Page 5) comment on Elliptic Curve certificates and while appearing to make a broad recommendation about it, don't seem to specifically compare RSA to ECDSA:
![image](https://user-images.githubusercontent.com/4291448/70030217-d8b67700-15fc-11ea-8321-50c7ae176011.png)

**Comment by perlboy** [comment]
Still no answer on this? Are implementers meant to be building for certificates signed by a CA using any algorithm other than RSA?

**Comment by perlboy** [comment]
Hello?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thank you for the query and apologies for the delay in the reply.

The CDR Register currently issues RSA signed certificates to participants. 

I cannot predict the future however Elliptical Curve certificates are not on our roadmap. Any introduction of a new certificate type will require an analysis period to verify impact and I would expect will occur with significant lead time due to the impact to participant security models

**Comment by perlboy** [comment]
Thanks, closing.
