### ISSUE TITLE
Data Storage Security Guidelines

### ISSUE THREAD

**Issue by perlboy** [cdr-register/register#37]
Hi there,

Somewhat related to #36 we have the following additional query. Can the ACCC provide some guidance regarding the governments expectations with respect to data at rest encryption to be used for Recipients storing Consumer data?

Our view at the moment is that Holder's are currently covered by APRA CPG234 and the related controls mitigate the impacts of encryption methods but the [draft accreditation guidelines](https://www.accc.gov.au/focus-areas/consumer-data-right-cdr-0/cdr-draft-accreditation-guidelines) and linked material make only broad references to encryption without any specific stipulation of expected encryption lifetimes, key lengths etc.

The choices around this may introduce the requirement for Hardware Security Module's for Recipients which have a reasonably large cost. Either way, configuration of these devices is rigid making retrospective re-encryption to future higher standards a significant task.

**Comment by perlboy** [comment]
Mic check?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your question.

The CDR Rules do not specify a particular method of encryption.  It is incumbent on ADRs to ensure that appropriate encryption is implemented in order to meet their security obligations and protect CDR data.  In determining what encryption methods to apply, an ADR must have regard to the CDR data that it holds and the security risks and threats that apply to it.  At this stage, the ACCC is not planning to require that particular encryption methods be adopted by participants.

**Comment by CDR-Register-Stream** [comment]
Closing as response has been provided. If you have any further questions, please feel free to raise a new issue
