### ISSUE TITLE
Feedback 40: SSA design updates to support ID Token encryption options

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#40]
As stated in the CDS:

*ID Tokens are specified in section 2 of the [OIDC] standard. In accordance with [FAPI-RW], ID Tokens must be signed and encrypted when returned to a Data Recipient from both the Authorisation End Point and Token End Point.*

Currently the Register Dynamic Client Registration design does not cater for encryption algorithm selection. To support ID token encryption, the Registration request would need to support the additional fields:
`id_token_encrypted_response_alg`
`id_token_encrypted_response_enc`
https://openid.net/specs/openid-connect-registration-1_0.html

**Comment by perlboy** [comment]
Is there a reason why the register isn't listing all valid parameters specified in [Client Metadata](https://openid.net/specs/openid-connect-registration-1_0.html#ClientMetadata) then perhaps altering OPTIONAL to MANDATORY? 

If the requester supplied attributes which are OIDC-DR compliant but not in the Register list will the request be rejected?

I'm not sure of the logic in being explicit about this, the workflow seems pretty clear:
1) Verify the request is a valid OIDC-DR format
2) Verify the source requester is authorised to retrieve an SSA by verifying the signature for which it was signed.
3) Issue signed SSA that contains the appropriate Registration request with the Register's endorsement

It seems if a common library is in use and chooses to add attributes which are optional but valid for OIDC-DR but not for Register there will be convergence issues once the SSA is returned as the content may be altered in-flight and therefore fail future checksum'ing when presented to the Holder.

**Comment by anzbankau** [comment]
ANZ has already implemented and shared its approach of using default encryption for ID token encryption. This aligns with the current standard and in our view is sufficient for the initial release.

ANZ would also support the removal of the ID token encryption (assuming the personalisation information is removed) as posted by Westpac in issue https://github.com/cdr-register/register/issues/38. We suggest this would simplify the ecosystem but not diminish the security profile. 

If ID token encryption is deemed necessary for the initial release, then we propose default encryption is sufficient. The introduction of the id_token_encrypted_response_alg field could be made in a later release, following an appropriate change management process.

**Comment by perlboy** [comment]
> ANZ has already implemented and shared its approach of using default encryption for ID token encryption. This aligns with the current standard and in our view is sufficient for the initial release.

"Default" is not an encryption algorithm. Arbitrarily setting an encryption method rather than using global method of discovery is implementation specific and sounds like future tech debt. @pcurtisrab has been commenting on this in #38 and consumerdatastandardsaustralia/standards-maintenance#58. What is proposed seems like a reasonable starting point.

**Comment by pcurtisrab** [comment]
@anzbankau, can you please cite your approach for default encryption for us to reference? We have [described our own concerns here](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/58).

Our paraphrased reading of `id_token_encrypted_response_alg` in [OIDC Registration](https://openid.net/specs/openid-connect-registration-1_0.html) is that if it is not specified, then by default, no ID Token Encryption is performed.

Therefore, by virtue of [CDS](https://consumerdatastandardsaustralia.github.io/standards/#tokens) already mandating the encryption of ID Tokens, it is already implied that `id_token_encrypted_response_alg` is REQUIRED, and the [normative standard](https://cdr-register.github.io/register/#registration-request-using-jwt) should be updated to clearly reflect that.

It is worth noting that the OpenID Provider may reject the registration request if the `id_token_encrypted_response_alg` or `id_token_encrypted_response_enc` is not supported. So in addition to the proposal, to ensure that registration requests have a low chance of being rejected, we suggest that selected algorithms are elevated to _Required_ as described in this [change request](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/58).

We are also open to making ID Token encryption optional, in the manner we have described in that request as the "Alternative solution".

**Comment by WestpacOpenBanking** [comment]
We believe that adding the proposed id_token_encrypted_response_alg field to the register SSA design is a reasonable approach, but remark that as a very recent change, implementation will be challenging within the time left for February.  
 
If the proposed change is made, then the id_token_encrypted_response_enc field should also be added to the register SSA design – otherwise a default value of A128CBC-HS256 would be assumed as per the [OIDC dynamic client registration specifications](https://openid.net/specs/openid-connect-registration-1_0.html#rfc.section.2)s.
 
As [previously noted](https://github.com/cdr-register/register/issues/38), and [supported by Commonwealth Bank](https://github.com/cdr-register/register/issues/38#issuecomment-562428022), we believe that removal of ID token encryption is the most pragmatic approach in support of a February implementation. We recommend this on the basis that the [standard state](https://consumerdatastandardsaustralia.github.io/standards/#id-token) that:
* “The ID Token returned from the Authorisation End Point MUST NOT contain any Personal Information (PI) claims.”
* [TLS-MA is required from the token endpoint](https://consumerdatastandardsaustralia.github.io/standards/#token-end-point) and [public clients](https://consumerdatastandardsaustralia.github.io/standards/#oidc-client-types) are not supported.
 
If encryption is to be supported, we support the approach [described](https://github.com/cdr-register/register/issues/38#issuecomment-564795663) by Regional Australia Bank.

**Comment by commbankoss** [comment]
Commonwealth Bank advocates for deferral of ID token encryption until a later date when appropriate use case is identified and encryption algorithms is agreed on. 
 
If encryption is enforced now, supported encryption algorithms should be advertised using OIDC discovery endpoint. Commonwealth bank currently supports RSA-OAEP-2048 encryption algorithm.

**Comment by omahoco** [comment]
86400 supports the CBA and Westpac position that deferral of ID token encryption is the most pragmatic option, given the timeframes the programme is operating to.

**Comment by NationalAustraliaBank** [comment]
NAB supports ID Token encryption being optional. As ID Tokens will not contain PI data via authorisation endpoint, there seems no appreciable benefit to encrypting the token.

**Comment by CDR-Register-Stream** [comment]
Description has been updated to specify both fields: 
`id_token_encrypted_response_alg`, `id_token_encrypted_response_enc`

Description has also been clarified that it is the Registration request, not the SSA which will need to include these fields

**Comment by CDR-Register-Stream** [comment]
Thank you all for you input on this issue.

ID token encryption and signing is required as per the [Consumer Data Standards](https://consumerdatastandardsaustralia.github.io/standards/#tokens)

The CDR Register design for [Registration Requests using JWT](https://cdr-register.github.io/register/#registration-request-using-jwt) has been updated to facilitate this support.

`id_token_encrypted_response_alg` and `id_token_encrypted_response_enc` fields have been incorporated into the registration request description
