### ISSUE TITLE
Feedback 41 - Access Token issuance for Registration Maintenance OR CDS APIs

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#41]
With the introduction of Client Registration maintenance flows, there are now two different categories of calls which DH issued access tokens should be used for:
	1. [Client Registration Management](https://cdr-register.github.io/register/#client-registration-management)
	2. [CDS APIs](https://consumerdatastandardsaustralia.github.io/standards/#authorisation-scopes)

The Register design already defines the following scopes for these categories:

- bank:accounts.basic:read
- bank:accounts.detail:read
- bank:transactions:read
- bank:payees:read
- bank:regular_payments:read
- common:customer.basic:read
- common:customer.detail:read
- cdr:registration

There has been a proposal that access tokens issued for Client Registration maintenance flows should not be  used for CDS APIs and vice versa.

The ACCC is requesting feedback for mandating that when ADRs request access tokens from DHs, they explicitly specify the scopes they require.

Data Holders will be required to check the scopes on access tokens to ensure they are dedicated for use in either Client Registration Management OR CDS APIs

**Comment by pcurtisrab** [comment]
In the current form of the standard, there does not appear to us (Regional Australia Bank) be a clear risk with DCR-issued tokens being used against the CDS APIs (since they will not map to consumer data).

It appears there may be more scope for abuse where CDS API-issued tokens are somehow used to access the registration API to, for example, delete or update a client registration.

In principle, as central entities in the ecosystem, it seems to makes sense for data holders to implement further protections for the benefit of the entire ecosystem. There appears to be sufficient risk avoided by clearly separating the possible scopes of access tokens obtained from different sources.

Given this rudimentary analysis Regional Australia Bank supports the proposal.

**Comment by WestpacOpenBanking** [comment]
We support the separation of concerns for access tokens as proposed. Logically, it does not make sense to implement a system where either:
* A consent is formed which enables editing of a Data Recipient’s client registration metadata.
* A token can be obtained for access to data APIs that are not linked to an customer or account data.

**Comment by omahoco** [comment]
86400 agree with the proposal that access tokens issued for client registration flows should not be used for CDS APIs and vice versa.

**Comment by NationalAustraliaBank** [comment]
NAB supports the proposal that ADR's Access Token scope request can contain either:

- cdr:registration

or one or more of the below.

- bank:accounts.basic:read
- bank:accounts.detail:read
- bank:transactions:read
- bank:payees:read
- bank:regular_payments:read
- common:customer.basic:read
- common:customer.detail:read

However the requirement for DH's to enforce this be delivered at a later date.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your input on this issue. 

The [CDR Register design](https://cdr-register.github.io/register/#authorisation-server) has been updated so access token issuance is separated for Registration maintenance glows and consuming CDS APIs
