### ISSUE TITLE
Feedback 42 - Revisiting Metadata Update requirements for Data Recipients

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#42]
The current Register design mandates that Data Recipients expose an Admin API to facilitate the [Metadata Update endpoint]( https://consumerdatastandardsaustralia.github.io/standards/#metadata-update)

The original requirement was to allow Data Holder security information to propagate to the Data Recipients in near-real-time through the push notification mechanism driven by the Register.

However, discussions on ecosystem change management have indicated that security information won't be changed on the fly and is more likely to be released in a more controlled manner.

Data Recipients are already required to poll the [GetDataHolderBrands API](https://cdr-register.github.io/register/#getdataholderbrands) every 6 hours to keep their Metadata Cache up to date. The current thinking is that this will be sufficient to propagate Data Holder Brand information (security and otherwise) through to the Data Recipients in the ecosystem.

We are proposing to remove the requirement for Data Recipients to host the Metadata Update endpoint for the initial release. Once the ecosystem is more mature, the requirement for Data Recipients hosting the Metadata Update endpoint will be revisited.

The ACCC is requesting feedback from the community on whether the assumptions being made on propagation of Data Holder security information is aligned to the thinking of current and future Data Holders.

**Comment by commbankoss** [comment]
Commonwealth Bank supports the recommendation to remove meta data refresh from ADRs and Data Holders.

**Comment by pcurtisrab** [comment]
As a future Data Holder, Regional Australia Bank will be interested in how we can minimise durations of broken connectivity in order to ensure that our members experience optimal service uptime in Data Recipient products.

We would only forsee the need to update endpoint data due to major infrastructure changes. However, we foresee some potential deployment planning issues in not knowing the timing of 6-hour or less intervals chosen by Data Recipients. We can only assume that Data Recipients will take  steps to react quickly in order to provide a quality continuous service.

To that end (from a Data Recipient standpoint) we would like the Metadata update to remain as an option, while not mandatory, for Data Recipients to use as a simple mechanism to react as quickly as possible.

**Comment by mattp-rab** [comment]
We don't see how see how this change would affect our obligations as a Data Holder as all metadata updates from the DH are to be manually provided to the ACCC register (correct me if I'm wrong). 

However we would like the event-based push notification functionality of metadata updates to ADRs by the ACCC register to remain in place with a modified requirement such that it is **optional** for ADRs to host an end-point. We see it as a potentially beneficial function depending on use-cases, so leaving it optional for ADRs provides that flexibility if required. We are intending to use this functionality as an ADR for our use-case.

**Comment by WestpacOpenBanking** [comment]
We support the removal of this endpoint.

**Comment by omahoco** [comment]
86400 supports the removal of the metadata refresh API.

**Comment by mattp-rab** [comment]
To be clear on our position, we suggest changing the requirement from mandatory to optional. This satisfies the desires of those who do not wish to host the endpoint as well as those that want to be more responsive.

**Comment by spikejump** [comment]
Intuit supports the removal of the metadata refresh API call for DRs.

In addition, can there be clarification on the 6-hour refresh call to getDataHolders for DRs?  As is the spec seems to show a sequence diagram of DH regularly polling for getSoftwareProductStatus.  No corresponding diagram for DR polling getDataHolders.

Moreover, what kind of changes are DRs expected to detect and react based on changes in the metadata returned from getDataHolders?  Can this be clarified?

As documented, the following scenarios may warrant a push notification.

> 1. A new Data Holder becomes active
> 1. A new Accredited Data Recipient software product becomes active
> 1. A Data Holder has been surrendered from the CDR
> 1. An Accredited Data Recipient Software Product has been deactivated or removed from the CDR Register

1 & 3 are relevant to ADRs.  How frequently will 3 happen?  For 1, our assumption is ADRs will make a conscious decision to connect to the new DH and would not systematically establish connections simply because a new DH is on the scene.

**Comment by NationalAustraliaBank** [comment]
NAB supports the recommendation to remove meta data refresh from Data Recipients.

**Comment by CDR-Register-Stream** [comment]
Thank you all for your feedback on this issue.
Metadata update requirements for Data Recipients has now been removed.

The [CDR Register](https://cdr-register.github.io/register/#ecosystem-component-diagram) design no longer requires Data Recipients build out any portion of the Admin API
