### ISSUE TITLE
Clarification on grant_type request parameter

### ISSUE THREAD

**Issue by WestpacOpenBanking** [cdr-register/register#44]
The register standard for [CDR Register Calling Participant Admin API](https://cdr-register.github.io/register/#cdr-register-calling-participant-admin-api-using-client-authentication) using Client Authentication omits the grant_type request parameter while still supplying other parameter consistent with a client credentials grant. This omission requires us to add a customisation in our security infrastructure which inserts a grant_type=client_credentials parameter into the request before we process it further. We request clarification on why this parameter was omitted and whether it can be added.

**Comment by CDR-Register-Stream** [comment]
Thanks for your query.
The client authentication section has been subsequently updated since you've raised this issue and the duplication of client authentication mechanisms has been removed.

Please refer to the CDR Register [Client Authentication section](https://cdr-register.github.io/register/#client-authentication) and note that it references the [Consumer Data Standards](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication).

Any further queries on this approach should be raised on the [CDS Standards Maintenance Repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance)
