### ISSUE TITLE
RegisterDataHolderAuth needs to facilitate DH to DR client authentication

### ISSUE THREAD

**Issue by CDR-Register-Stream** [cdr-register/register#81]
Currently the [RegisterDataHolderAuth](https://cdr-register.github.io/register/#tocSregisterdataholderauth) schema definition contains a jwksEndpoint referenced in DH to ADR client authentication as detailed in [standards security profile](https://consumerdatastandardsaustralia.github.io/standards/#client-authentication)

However, the registerUType enumeration contains the value HYBRIDFLOW-JWKS. This is incorrect as this jwksEndpoint is not used in this flow. Within the HYBRIDFLOW, the DR authenticates with the DH and the details are captured in the SSA in [Dynamic Client Registration](https://cdr-register.github.io/register/#dynamic-client-registration)

To be meaningful, this enumeration needs to be updated with a value representing the DH to DR client authentication mechanism

Considering renaming this value in the enumeration to: SIGNED-JWT

**Comment by NationalAustraliaBank** [comment]
NAB do not see any issue with the proposal.

**Comment by perlboy** [comment]
This seems to be related to #67.

Is there a reason this is required at all? If the Holder is contacting the Recipient with a signed request it should be signed by the Holder with an `iss` that matches what is in the register (presumably the `iss` from the Discovery document retrieved from the infosec endpoint). 

Since it matches what is in the register it would contain a discovery document which would contain a link to a JWKS. On this basis normal discovery procedures can occur to validate a signed JWT.

It's all kind of moot though because the Revocation specification in the CDS looks to be non-functional on the basis it requests an RFC7009 formatted revocation request but then also requests it contain an `sub` of the Holder (which a Holder issued token would **never** have because Holder issued tokens to Recipients for Consumers have a pairwise `sub`).

Has the ACCC or the DSB **actually** tested this in a real deployment yet?

**Comment by CDR-Register-Stream** [comment]
@perlboy Thanks for your contribution to this topic. We have several tickets on this topic so I have raised #118 to revisit this topic and track it there.

I will therefore close this ticket as complete, The enum value HYBRIDFLOW-JWKS has been renamed to SIGNED-JWT to reduce confusion
